### ISSUE TITLE
IncomingInvoiceVoucherService.SaveAsync does not return voucher with valid VoucherNumber

### ISSUE THREAD

**Issue by frankhaugen** [PowerOffice/go-api#12]
When using the SaveAsync() method to Post an incoming invoice, I would expect the response to have been filled in with PowerOffice -generated data. However, this seems not to be happening: 
![image](https://user-images.githubusercontent.com/13543585/133275867-9ba1cd88-e9c0-4cf7-bdc1-495e09ccba77.png)

It's not described in docs the expected behaviour, but as the ID is generated and returned, I would think VoucherNumber also should be. I can do a get on the invoice to get the voucher number, but this seems to be a bit wastefull when it comes to the fact that I'm doing an extra call to your API.

Our need for VoucherNumber is for legal purposes, so we need to get it, but I'd prefer to not do a second call to get the entire invoice for only one field.

Is this anything you can/will fix?

**Comment by frankhaugen** [comment]
Correction! Even getting the invoice after creation sometimes don't return an invoice with a valid voucher number

**Comment by rodfjell** [comment]
Hi,

Sorry for the late reply.

The behaviour you are experiencing is due to how voucher numbers are assigned in our system. To ensure that all voucher numbers are correctly ordered after creation date, we have a high priority background thread that assigns them right after a voucher is added to our databases. If the traffic is high on this background worker role, it might not be done completing assignment of the voucher number before the API server response is queried out and returned. In these instances you will receive a negative voucher number.

We will not change this behaviour right now, but I will update the nuget package and web documentation on our next release describing the behaviour. Current workaround for API clients is to call a GET abit after saving the voucher if the voucher number is negative, and continue to do so until the voucher number is assigned (has a positive value).

**Comment by frankhaugen** [comment]
@rodfjell thank you for the response. Not an optimal situation, but thank you for adding it to docs.

For anyone stumbling over this issue, here's my solution that seems to do the trick:
```C#
var response = await _goClient.Voucher.IncomingInvoice.SaveAsync(invoiceVoucher);

while (response.VoucherNo < 0)
{
    Thread.Sleep(250);
    response = await _goClient.Voucher.IncomingInvoice.GetAsync(response.Id.GetValueOrDefault());
}
```
