### ISSUE TITLE
Filtering customer by LastChanged and CreateDate fails

### ISSUE THREAD

**Issue by willmakenoise** [PowerOffice/go-api#14]
Hi!

Whenever I try to filter customers by the fields 'LastChanged' and 'CreateDate' I get an OData Exception in return.

Examples of filters that return the error:
`$filter=(LastChanged ge DateTime'2020-01-01T00:00:00').`
`$filter=(LastChanged ge DateTime'2020-01-01').`
`$filter=(LastChanged ge DateTime'2020-01-01T00:00:00 +00:00').`

Filtering by datetime on the customer field 'Since' does work.
Filtering products by 'LastChanged' does work.

Being able to filter all models by 'LastChanged' helps a lot with keeping data transfers and computation at a minimum.

I hope you can look into this issue. Thanks 😀

**Comment by kridah** [comment]
Hi,

This error probably occurs because you're using DateTime when the API expects DateTimeOffset. This query should work:
`/customer/?$filter=(LastChanged ge DateTimeOffset'2020-01-01T00:00:00')`
Note: Hours, minutes and seconds are optional and I could not get that last query (with +00:00) to work.

**Comment by willmakenoise** [comment]
Thanks @kridah !

I can't find this in the documentation.

**Comment by adrianAtProresult** [comment]
I just lost half an hour too because the data type `DateTimeOffset` is not mentioned anywhere in the documentation. `LastChanged` in [Project](https://api.poweroffice.net/Web/docs/index.html#Reference/Rest/Type_Project.md) is only listed as being of type `Date`, and the filtering page and the pages linked from there fail to mention it too. If `DateTimeOffset` would be mentioned below the `DateTime` example with its own example, I think a lot of devs will save time. Hope you'll consider adding this to the [filtering](https://api.poweroffice.net/Web/docs/index.html#Rest/Filtering.md) documentation page!

**Comment by kridah** [comment]
Hi! We just updated our docs. In general LastChanged and CreatedDate are DateTimeOffset.
<img width="919" alt="image" src="https://github.com/PowerOffice/go-api/assets/10164781/d354fafb-1476-46ea-8e3e-237cb264334b">

**Comment by adrianAtProresult** [comment]
@kridah Excellent! Thank you. :)
